import json
from datetime import datetime
from app import get_chemical_from_db, insert_chemical_to_db, fetch_chemical_from_pubchem

def batch_import_chemicals(names):
    for name in names:
        print(f"Processing: {name}")
        # Check if chemical is already in DB
        existing = get_chemical_from_db(name)
        if existing:
            print(f" - Already in DB, skipping.")
            continue

        # Fetch from PubChem
        chemical = fetch_chemical_from_pubchem(name)
        if chemical:
            insert_chemical_to_db(name, chemical)
            print(f" - Fetched and inserted.")
        else:
            print(f" - Not found on PubChem.")

if __name__ == "__main__":
    # Corrected list with commas and unescaped entities
    chemical_names = [
        "Acetaldehyde",
        "Acrolein (2-Propenal)",
        "Acrylyl Chloride",
        "Allyl Chloride",
        "Allylamine",
        "Alkylaluminums",
        "Ammonia, Anhydrous",
        "Ammonia solutions (>44% ammonia by weight)",
        "Ammonium Perchlorate",
        "Ammonium Permanganate",
        "Arsine (also called Arsenic Hydride)",
        "Bis(Chloromethyl) Ether",
        "Boron Trichloride",
        "Boron Trifluoride",
        "Bromine",
        "Bromine Chloride",
        "Bromine Pentafluoride",
        "Bromine Trifluoride",
        "3-Bromopropyne (also called Propargyl Bromide)",
        "Butyl Hydroperoxide (Tertiary)",
        "Butyl Perbenzoate (Tertiary)",
        "Carbonyl Chloride (see Phosgene)",
        "Carbonyl Fluoride",
        "Cellulose Nitrate (concentration >12.6% nitrogen)",
        "Chlorine",
        "Chlorine Dioxide",
        "Chlorine Pentrafluoride",
        "Chlorine Trifluoride",
        "Chlorodiethylaluminum (also called Diethylaluminum Chloride)",
        "1-Chloro-2,4-Dinitrobenzene",
        "Chloromethyl Methyl Ether",
        "Chloropicrin",
        "Chloropicrin and Methyl Bromide mixture",
        "Chloropicrin and Methyl Chloride mixture",
        "Cumene Hydroperoxide",
        "Cyanogen",
        "Cyanogen Chloride",
        "Cyanuric Fluoride",
        "Diacetyl Peroxide (Concentration >70%)",
        "Diazomethane",
        "Dibenzoyl Peroxide",
        "Diborane",
        "Dibutyl Peroxide (Tertiary)",
        "Dichloro Acetylene",
        "Dichlorosilane",
        "Diethylzinc",
        "Diisopropyl Peroxydicarbonate",
        "Dilaluroyl Peroxide",
        "Dimethyldichlorosilane",
        "Dimethylhydrazine, 1,1-",
        "Dimethylamine, Anhydrous",
        "2,4-Dinitroaniline",
        "Ethyl Methyl Ketone Peroxide (also Methyl Ethyl Ketone Peroxide; concentration >60%)",
        "Ethyl Nitrite",
        "Ethylamine",
        "Ethylene Fluorohydrin",
        "Ethylene Oxide",
        "Ethyleneimine",
        "Fluorine",
        "Formaldehyde (Formalin)",
        "Furan",
        "Hexafluoroacetone",
        "Hydrochloric Acid, Anhydrous",
        "Hydrofluoric Acid, Anhydrous",
        "Hydrogen Bromide",
        "Hydrogen Chloride",
        "Hydrogen Cyanide, Anhydrous",
        "Hydrogen Fluoride",
        "Hydrogen Peroxide (52% by weight or greater)",
        "Hydrogen Selenide",
        "Hydrogen Sulfide",
        "Hydroxylamine",
        "Iron, Pentacarbonyl",
        "Isopropylamine",
        "Ketene",
        "Methacrylaldehyde",
        "Methacryloyl Chloride",
        "Methacryloyloxyethyl Isocyanate",
        "Methyl Acrylonitrile",
        "Methylamine, Anhydrous",
        "Methyl Bromide",
        "Methyl Chloride",
        "Methyl Chloroformate",
        "Methyl Ethyl Ketone Peroxide (concentration >60%)",
        "Methyl Fluoroacetate",
        "Methyl Fluorosulfate",
        "Methyl Hydrazine",
        "Methyl Iodide",
        "Methyl Isocyanate",
        "Methyl Mercaptan",
        "Methyl Vinyl Ketone",
        "Methyltrichlorosilane",
        "Nickel Carbonly (Nickel Tetracarbonyl)",
        "Nitric Acid (94.5% by weight or greater)",
        "Nitric Oxide",
        "Nitroaniline (para Nitroaniline",
        "Nitromethane",
        "Nitrogen Dioxide",
        "Nitrogen Oxides (NO; NO2; N204; N203)",
        "Nitrogen Tetroxide (also called Nitrogen Peroxide)",
        "Nitrogen Trifluoride",
        "Nitrogen Trioxide",
        "Oleum (65% to 80% by weight; also called Fuming Sulfuric Acid)",
        "Osmium Tetroxide",
        "Oxygen Difluoride (Fluorine Monoxide)",
        "Ozone",
        "Pentaborane",
        "Peracetic Acid (concentration >60% Acetic Acid; also called Peroxyacetic Acid)",
        "Perchloric Acid (concentration >60% by weight)",
        "Perchloromethyl Mercaptan",
        "Perchloryl Fluoride",
        "Peroxyacetic Acid (concentration >60% Acetic Acid; also called Peracetic Acid)",
        "Phosgene (also called Carbonyl Chloride)",
        "Phosphine (Hydrogen Phosphide)",
        "Phosphorus Oxychloride (also called Phosphoryl Chloride)",
        "Phosphorus Trichloride",
        "Phosphoryl Chloride (also called Phosphorus Oxychloride)",
        "Propargyl Bromide",
        "Propyl Nitrate",
        "Sarin",
        "Selenium Hexafluoride",
        "Stibine (Antimony Hydride)",
        "Sulfur Dioxide (liquid)",
        "Sulfur Pentafluoride",
        "Sulfur Tetrafluoride",
        "Sulfur Trioxide (also called Sulfuric Anhydride)",
        "Sulfuric Anhydride (also called Sulfur Trioxide)",
        "Tellurium Hexafluoride",
        "Tetrafluoroethylene",
        "Tetrafluorohydrazine",
        "Tetramethyl Lead",
        "Thionyl Chloride",
        "Trichloro (chloromethyl) Silane",
        "Trichloro (dichlorophenyl) Silane",
        "Trichlorosilane",
        "Trifluorochloroethylene",
        "Trimethyoxysilane",
    ]

    batch_import_chemicals(chemical_names)

    print("Batch import completed.")
